import React,{Component} from 'react'
import {hashHistory,Link} from 'react-router'
import style from '../css/detail.css'
import Modal from './Modal'
import productsDate from '../data/productsDate.json'
